Repository zero-to-mastery/Canvas-Creations, pull requests merged in 2020-10, with the labels that each got.

#12 Canvas play
  Art/ravi/German_Flag.jpg
  Art/ravi/index.html
  Art/ravi/script.js
  Art/ravi/style.css
  include.js
Labels: Conflict Present

#180 added irish flag
  Art/max/irishflag.css
  Art/max/irishflag.html
  Art/max/irishflag.js
  Art/max/irishflag.png
  include.js
Labels: Conflict Present

#195 Add canvas
  Art/.DS_Store
  Art/dekisr/hadoken.gif
  Art/dekisr/index.html
  Art/dekisr/main.js
  Art/dekisr/style.css
  include.js
Labels: Needs Revision

#194 canadian flag on html canvas
  Art/Ozziel/app.js
  Art/Ozziel/canadaflag.png
  Art/Ozziel/img/red-leaf.png
  Art/Ozziel/index.html
  Art/Ozziel/styles.css
  include.js
  package-lock.json
Labels: Conflict Present

#228 Furi
  Art/Furuikeya/index.html
  Art/Furuikeya/script.js
  Art/Furuikeya/style.css
  Art/Furuikeya/ztm.png
  include.js
Labels: question
